const COPY = {
  running: "● Running",
  stopped: "○ Stopped",
  waitingForLogin: "Waiting for sign-in",
  notSignedIn: "Not signed in",
  newAccount: "New account",
  label: "Label",
  color: "Color",
  preset: "Global preset",
  create: "Create",
  noAccount:
    "Create an account, then launch Claude Desktop and sign in with that Claude Max subscription.",
  launchDesktop: "Launch Desktop",
  signIn: "Sign in",
  stop: "Stop",
  launchCode: "Open Claude Code",
  openFolder: "Open folder",
  delete: "Delete",
  confirmDelete: "Click again to delete",
  identity: "Identity",
  desktopAccount: "Desktop account",
  codeAccount: "Claude Code account",
  unknown: "—",
  unbound: "Not bound yet. The first account that signs in is bound automatically.",
  matching: "Matches the bound Claude account.",
  mismatch: (expected: string, actual: string): string =>
    `Signed in as ${actual}, but this environment is bound to ${expected}.`,
  bind: "Bind to the current sign-in",
  synced: "Files are in sync.",
  skipped: (names: string): string => `Skipped because they are links: ${names}`,
  missingSecrets: (names: string): string => `Missing secrets: ${names}`,
  syncFailed: (message: string): string => `Could not write files: ${message}`,
  settings: "Settings",
  save: "Save",
  override: "Override (wins over the Global preset for this account only)",
  overrideHelp:
    "JSON with disabledMcp, mcp, codeSettings and rules. Use {{secret:NAME}} for credentials.",
  secrets: "Secrets (this account only, encrypted with Windows DPAPI)",
  secretName: "Name",
  secretValue: "Value",
  addSecret: "Save secret",
  remove: "Remove",
  paths: "Folders",
} as const;

export { COPY };
